carrent/account/urls.py
from django.urls import path
from .views import (
	RegisterClientView,
	RegisterEmployeeView,
	UserPermissionsView,
	UserIdView,
	ClientDetailView,
	ClientUpdateView,
	ClientListView,
	ClientDeleteView,
	EmployeeListView,

	EmailActivateView,
	PasswordChangeView,
	PasswordChangeRequestView,
)

app_name = 'account'

urlpatterns = [
	path('user/client/register/', RegisterClientView.as_view(), name='register-client'),
	path('user/employee/register/', RegisterEmployeeView.as_view(), name='register-employee'),
	path('user/permissions/', UserPermissionsView.as_view(), name='user-permissions'),
	path('user/id/', UserIdView.as_view(), name='user-id'),
	path('user/client/', ClientDetailView.as_view(), name='client-detail'),
	path('user/client/update/', ClientUpdateView.as_view(), name='client-update'),
	path('user/clients/', ClientListView.as_view(), name='client-list'),
	path('user/delete/<int:id>/', ClientDeleteView.as_view(), name='client-delete'),
	path('user/employees/', EmployeeListView.as_view(), name='employee-list'),

	path('activate/<uidb64>/<token>', EmailActivateView.as_view(), name='email-activate'),
	path('passwordchange/', PasswordChangeView.as_view(), name='password-change'),
	path('passwordchange/request/', PasswordChangeRequestView.as_view(), name='password-change-request'),
]

carrent/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
	TokenObtainPairView,
	TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),

# account URLs import
    path('api/', include('carrent.account.urls')),

# car URLs import
    path('api/car/', include('carrent.car.urls')),

# rents URLs import
    path('api/rent/', include('carrent.rents.urls')),

# issues URLs import
    path('api/issue/', include('carrent.issues.urls')),

# JSON Web Token Endpoints
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/refresh/', TokenRefreshView.as_view()),
]


# Additional imports to set up Media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
# We need to make Custom User Manager first
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _


class CustomUserManager(BaseUserManager):
	"""
	Custom User Manager where user, and superuser is created
	based on email, not username.
	"""
	def create_user(self, email, password, **extra_fields):

		if not email:
			raise ValueError(_("Email is required"))

		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save()

		return user

	def create_superuser(self, email, password, **extra_fields):

		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		extra_fields.setdefault('is_active', True)

		return self.create_user(email, password, **extra_fields)


# Then we are making Custo User Model
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime


class User(AbstractUser):
	"""
	Custom User Model
	"""
	email 				= models.EmailField(unique=True)
	is_client 			= models.BooleanField(default=False)
	is_employee 		= models.BooleanField(default=False)
	username			= None

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = CustomUserManager()	

	def __str__(self):
		return f"Name: {self.first_name} {self.last_name} e-mail: {self.email}"


class Client(models.Model):
	"""
	Table with extra fields for Client
	Releted to the User
	"""
	user 				= models.OneToOneField(User, on_delete=models.CASCADE)
	driver_license		= models.CharField(max_length=20, unique=True)
	city 				= models.CharField(max_length=30)
	street 				= models.CharField(max_length=30)
	street_number 		= models.CharField(max_length=10)
	postal_code 		= models.CharField(max_length=10)
	phone_number 		= models.CharField(max_length=20)
	birth_day 			= models.DateField(default=datetime.date.today)

account/views.py
from rest_framework import status, permissions
from carrent.permissions import (
		IsEmployee,
		IsSuperuser,
	)
from rest_framework.response import Response
from rest_framework.views import APIView
from account.api.serializers import (
		RegisterClientSerializer,
		EmployeeSerializer,
		UserPermissionsSerializer,
		UserIdSerializer,
		ClientProfileSerializer,
		ClientUpdateSerializer,
		ClientsSerializer,
	)
from .models import User, Client
from account.helpers import (
		send_mail_password_reset,
		password_check,
	)
from .tokens import (
		token_generator,
		token_password_reset_generator,
	)


class RegisterClientView(APIView):
	"""
	Client Registration
	"""
	permission_classes = [permissions.AllowAny]

	def post(self, request):
		data = request.data

		serializer = RegisterClientSerializer(data=data)

		if serializer.is_valid():
			if password_check(data['password']):
				serializer.save()

				user = User.objects.get(email=data['email'])
				send_mail_confirmation(request, user, data['email'])

				return Response("We've sent you email", status=status.HTTP_201_CREATED)

			return Response('Your password is too weak', status=status.HTTP_400_BAD_REQUEST)

		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RegisterEmployeeView(APIView):
	"""
	Employee Registration
	"""
	permission_classes = [permissions.AllowAny]
	def post(self, request):
		data = request.data

		serializer = EmployeeSerializer(data=data)

		if serializer.is_valid():
			if password_check(data['password']):
				serializer.save()

				return Response("Account created", status=status.HTTP_201_CREATED)

			return Response('Password is too weak', status=status.HTTP_400_BAD_REQUEST)

		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserPermissionsView(APIView):
	"""
	GET request returning fields: 'is_client',
	'is_employee' and 'is_superuser'
	"""
	def get(self, request):
		serializer = UserPermissionsSerializer(request.user)

		return Response(serializer.data)


class UserIdView(APIView):
	"""
	GET request returning user ID
	of logged user
	"""
	def get(self, request):
		serializer = UserIdSerializer(request.user)

		return Response(serializer.data)

class PasswordChangeRequestView(APIView):
	"""
	POST request sending email
	with link where user can 
	change password
	"""
	permission_classes = [permissions.AllowAny]

	def post(self, request):
		try:
			user = User.objects.get(email=request.data['email'])
		except User.DoesNotExist:
			user = None
		if user:
			send_mail_password_reset(user)

			return Response('Email sent', status=status.HTTP_200_OK)

		return Response('Invalid email', status=status.HTTP_400_BAD_REQUEST)


class ClientDetailView(APIView):
	"""
	GET request returning all
	detail about logged client
	"""
	def get(self, request):
		serializer = ClientProfileSerializer(request.user, context={'request': request})

		return Response(serializer.data)


class ClientUpdateView(APIView):
	"""
	View updating some
	client data
	"""
	def put(self, request):
		"""
		PUT request for update
		"""
		data = request.data

		client = Client.objects.get(user=data['user'])

		serializer = ClientUpdateSerializer(client, data)

		if serializer.is_valid():
			serializer.save()

			return Response(status=status.HTTP_200_OK)

		return Response('Something went wrong', status=status.HTTP_400_BAD_REQUEST)

	def get(self, request):
		"""
		GET request for get
		user logged in data
		"""
		client = Client.objects.get(user=request.user)

		serializer = ClientUpdateSerializer(client)

		return Response(serializer.data)


class ClientListView(APIView):
	"""
	List of all clients
	"""
	permission_classes = [permissions.IsAuthenticated, IsEmployee]

	def get(self, request):
		queryset = User.objects.filter(is_client=True)
		serializer = ClientsSerializer(queryset, many=True)

		return Response(serializer.data)


class ClientDeleteView(APIView):
	"""
	Deleting client
	"""
	permission_classes = [permissions.IsAuthenticated, IsEmployee]

	def get_object(self, id):
		return User.objects.get(pk=id)

	def delete(self, request, id):
		user = self.get_object(id)

		if user:
			user.delete()

			return Response(status=status.HTTP_204_NO_CONTENT)

		return Response(status=status.HTTP_400_BAD_REQUEST)


class EmployeeListView(APIView):
	"""
	List of all employees
	"""
	permission_classes = [permissions.IsAuthenticated, IsSuperuser]

	def get(self, request):
		queryset = User.objects.filter(is_employee=True)

		serializer = EmployeeSerializer(queryset, many=True)

		return Response(serializer.data)


# Imports for email confirmation
from django.views import View
from .helpers import send_mail_confirmation
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import redirect


class EmailActivateView(View):
	"""
	View where user activates acc
	"""
	permission_classes = [permissions.AllowAny]

	def get(self, request, uidb64, token):
		try:
			uid = force_text(urlsafe_base64_decode(uidb64))
			user = User.objects.get(pk=uid)
		except (TypeError, ValueError, OverflowError, User.DoesNotExist):
			user = None

		if user is not None and token_generator.check_token(user, token):
			user.is_active = True
			user.save()

			return redirect("http://localhost:3000/login")
		else:
			return redirect('https://error404.com')


class PasswordChangeView(APIView):
	"""
	User sending coded ID,
	token and new password
	"""
	permission_classes = [permissions.AllowAny]

	def post(self, request):
		try:
			uid = force_text(urlsafe_base64_decode(request.data['uidb64']))
			user = User.objects.get(pk=uid)
		except (TypeError, ValueError, OverflowError, User.DoesNotExist):
			user = None

		if user is not None and token_password_reset_generator.check_token(user, request.data['token']):
			if password_check(request.data['password']):
				user.set_password(request.data['password'])
				user.save()

				return Response('Password changed', status=status.HTTP_200_OK)

			return Response('Your password is too weak', status=status.HTTP_400_BAD_REQUEST)

		return Response('Something went wrong', status=status.HTTP_400_BAD_REQUEST)

carrent/account/views.py
from rest_framework import status, permissions
from carrent.permissions import (
		IsEmployee,
		IsSuperuser,
	)
from rest_framework.response import Response
from rest_framework.views import APIView
from carrent.account.api.serializers import (
		RegisterClientSerializer,
		EmployeeSerializer,
		UserPermissionsSerializer,
		UserIdSerializer,
		ClientProfileSerializer,
		ClientUpdateSerializer,
		ClientsSerializer,
	)
from .models import User, Client
from carrent.account.helpers import (
		send_mail_password_reset,
		password_check,
	)
from .tokens import (
		token_generator,
		token_password_reset_generator,
	)


class RegisterClientView(APIView):
	"""
	Client Registration
	"""
	permission_classes = [permissions.AllowAny]

	def post(self, request):
		data = request.data

		serializer = RegisterClientSerializer(data=data)

		if serializer.is_valid():
			if password_check(data['password']):
				serializer.save()

				user = User.objects.get(email=data['email'])
				send_mail_confirmation(request, user, data['email'])

				return Response("We've sent you email", status=status.HTTP_201_CREATED)

			return Response('Your password is too weak', status=status.HTTP_400_BAD_REQUEST)

		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RegisterEmployeeView(APIView):
	"""
	Employee Registration
	"""
	permission_classes = [permissions.IsAuthenticated, IsSuperuser]
	def post(self, request):
		data = request.data

		serializer = EmployeeSerializer(data=data)

		if serializer.is_valid():
			if password_check(data['password']):
				serializer.save()

				return Response("Account created", status=status.HTTP_201_CREATED)

			return Response('Password is too weak', status=status.HTTP_400_BAD_REQUEST)

		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserPermissionsView(APIView):
	"""
	GET request returning fields: 'is_client',
	'is_employee' and 'is_superuser'
	"""
	def get(self, request):
		serializer = UserPermissionsSerializer(request.user)

		return Response(serializer.data)


class UserIdView(APIView):
	"""
	GET request returning user ID
	of logged user
	"""
	def get(self, request):
		serializer = UserIdSerializer(request.user)

		return Response(serializer.data)

class PasswordChangeRequestView(APIView):
	"""
	POST request sending email
	with link where user can 
	change password
	"""
	permission_classes = [permissions.AllowAny]

	def post(self, request):
		try:
			user = User.objects.get(email=request.data['email'])
		except User.DoesNotExist:
			user = None
		if user:
			send_mail_password_reset(user)

			return Response('Email sent', status=status.HTTP_200_OK)

		return Response('Invalid email', status=status.HTTP_400_BAD_REQUEST)


class ClientDetailView(APIView):
	"""
	GET request returning all
	detail about logged client
	"""
	def get(self, request):
		serializer = ClientProfileSerializer(request.user, context={'request': request})

		return Response(serializer.data)


class ClientUpdateView(APIView):
	"""
	View updating some
	client data
	"""
	def put(self, request):
		"""
		PUT request for update
		"""
		data = request.data

		client = Client.objects.get(user=request.user.id)

		serializer = ClientUpdateSerializer(client, data)

		if serializer.is_valid():
			serializer.save()

			return Response(status=status.HTTP_200_OK)

		return Response('Something went wrong', status=status.HTTP_400_BAD_REQUEST)

	def get(self, request):
		"""
		GET request for get
		user logged in data
		"""
		client = Client.objects.get(user=request.user)

		serializer = ClientUpdateSerializer(client)

		return Response(serializer.data)


class ClientListView(APIView):
	"""
	List of all clients
	"""
	permission_classes = [permissions.IsAuthenticated, IsEmployee]

	def get(self, request):
		queryset = User.objects.filter(is_client=True)
		serializer = ClientsSerializer(queryset, many=True)

		return Response(serializer.data)


class ClientDeleteView(APIView):
	"""
	Deleting client
	"""
	permission_classes = [permissions.IsAuthenticated, IsEmployee]

	def get_object(self, id):
		try:
			return User.objects.get(pk=id)
		except User.DoesNotExist:
			return False

	def delete(self, request, id):
		user = self.get_object(id)
		log_user = request.user

		if user:
			if (user.is_client and log_user.is_employee) or (log_user.is_superuser):
				user.delete()

				return Response(status=status.HTTP_204_NO_CONTENT)

			return Response(status=status.HTTP_403_FORBIDDEN)

		return Response(status=status.HTTP_400_BAD_REQUEST)


class EmployeeListView(APIView):
	"""
	List of all employees
	"""
	permission_classes = [permissions.IsAuthenticated, IsSuperuser]

	def get(self, request):
		queryset = User.objects.filter(is_employee=True)

		serializer = EmployeeSerializer(queryset, many=True)

		return Response(serializer.data)


# Imports for email confirmation
from django.views import View
from .helpers import send_mail_confirmation
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import redirect


class EmailActivateView(View):
	"""
	View where user activates acc
	"""
	permission_classes = [permissions.AllowAny]

	def get(self, request, uidb64, token):
		try:
			uid = force_text(urlsafe_base64_decode(uidb64))
			user = User.objects.get(pk=uid)
		except (TypeError, ValueError, OverflowError, User.DoesNotExist):
			user = None

		if user is not None and token_generator.check_token(user, token):
			user.is_active = True
			user.save()

			return redirect("http://34.118.16.167/login")
		else:
			return redirect('https://error404.com')


class PasswordChangeView(APIView):
	"""
	User sending coded ID,
	token and new password
	"""
	permission_classes = [permissions.AllowAny]

	def post(self, request):
		try:
			uid = force_text(urlsafe_base64_decode(request.data['uidb64']))
			user = User.objects.get(pk=uid)
		except (TypeError, ValueError, OverflowError, User.DoesNotExist):
			user = None

		if user is not None and token_password_reset_generator.check_token(user, request.data['token']):
			if password_check(request.data['password']):
				user.set_password(request.data['password'])
				user.save()

				return Response('Password changed', status=status.HTTP_200_OK)

			return Response('Your password is too weak', status=status.HTTP_400_BAD_REQUEST)

		return Response('Something went wrong', status=status.HTTP_400_BAD_REQUEST)

account/templates/email-template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html data-editor-version="2" class="sg-campaigns" xmlns="http://www.w3.org/1999/xhtml"><head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=Edge">
      <style type="text/css">
    body, p, div {
      font-family: inherit;
      font-size: 14px;
    }
    body {
      color: #000000;
    }
    body a {
      color: #1188E6;
      text-decoration: none;
    }
    p { margin: 0; padding: 0; }
    table.wrapper {
      width:100% !important;
      table-layout: fixed;
      -webkit-font-smoothing: antialiased;
      -webkit-text-size-adjust: 100%;
      -moz-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
    }
    img.max-width {
      max-width: 100% !important;
    }
    .column.of-2 {
      width: 50%;
    }
    .column.of-3 {
      width: 33.333%;
    }
    .column.of-4 {
      width: 25%;
    }
    @media screen and (max-width:480px) {
      .preheader .rightColumnContent,
      .footer .rightColumnContent {
        text-align: left !important;
      }
      .preheader .rightColumnContent div,
      .preheader .rightColumnContent span,
      .footer .rightColumnContent div,
      .footer .rightColumnContent span {
        text-align: left !important;
      }
      .preheader .rightColumnContent,
      .preheader .leftColumnContent {
        font-size: 80% !important;
        padding: 5px 0;
      }
      table.wrapper-mobile {
        width: 100% !important;
        table-layout: fixed;
      }
      img.max-width {
        height: auto !important;
        max-width: 100% !important;
      }
      a.bulletproof-button {
        display: block !important;
        width: auto !important;
        font-size: 80%;
        padding-left: 0 !important;
        padding-right: 0 !important;
      }
      .columns {
        width: 100% !important;
      }
      .column {
        display: block !important;
        width: 100% !important;
        padding-left: 0 !important;
        padding-right: 0 !important;
        margin-left: 0 !important;
        margin-right: 0 !important;
      }
    }
  </style>
      <!--user entered Head Start--><link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"><style>
body {font-family: 'Muli', sans-serif;}
</style><!--End Head user entered-->
    </head>
    <body>
      <center class="wrapper" data-link-color="blue" data-body-style="font-size:14px; font-family:inherit; color:blue; background-color:blue;">
        <div class="webkit">
          <table cellpadding="0" cellspacing="0" border="0" width="100%" class="wrapper" bgcolor="#FFFFFF">
            <tbody><tr>
              <td valign="top" bgcolor="#FFFFFF" width="100%">
                <table width="100%" role="content-container" class="outer" align="center" cellpadding="0" cellspacing="0" border="0">
                  <tbody><tr>
                    <td width="100%">
                      <table width="100%" cellpadding="0" cellspacing="0" border="0">
                        <tbody><tr>
                          <td>
                            <!--[if mso]>
    <center>
    <table><tr><td width="600">
  <![endif]-->
                                    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%; max-width:600px;" align="center">
                                      <tbody><tr>
                                        <td role="modules-container" style="padding:0px 0px 0px 0px; color:#0F0140; text-align:left;" bgcolor="#FFFFFF" width="100%" align="left"><table class="module preheader preheader-hide" role="module" data-type="preheader" border="0" cellpadding="0" cellspacing="0" width="100%" style="display: none !important; mso-hide: all; visibility: hidden; opacity: 0; color: blue; height: 0; width: 0;">
    <tbody><tr>
      <td role="module-content">
        <p></p>
      </td>
    </tr>
  </tbody></table><table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" role="module" data-type="columns" style="padding:30px 20px 30px 20px;" bgcolor="#F089C6">
    <tbody>
      <tr role="module-content">
        <td height="100%" valign="top">
          <table class="column" width="540" style="width:540px; border-spacing:0; border-collapse:collapse; margin:0px 10px 0px 10px;" cellpadding="0" cellspacing="0" align="left" border="0" bgcolor="">
            <tbody>
              <tr>
                <td style="padding:0px;margin:0px;border-spacing:0;"><table class="wrapper" role="module" data-type="image" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="72aac1ba-9036-4a77-b9d5-9a60d9b05cba">
    <tbody>
      <tr>
        <td style="font-size:6px; line-height:10px; padding:0px 0px 0px 0px;" valign="top" align="center">
        </td>
      </tr>
    </tbody>
  </table><table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="331cde94-eb45-45dc-8852-b7dbeb9101d7">
    <tbody>
      <tr>
        <td style="padding:0px 0px 20px 0px;" role="module-content" bgcolor="">
        </td>
      </tr>
    </tbody>
  </table><table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="27716fe9-ee64-4a64-94f9-a4f28bc172a0">
    <tbody>
      <tr>
        <td style="padding:0px 0px 30px 0px;" role="module-content" bgcolor="">
        </td>
      </tr>
    </tbody>
  </table><table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="948e3f3f-5214-4721-a90e-625a47b1c957" data-mc-module-version="2019-10-22">
    <tbody>
      <tr>
        <td style="padding:50px 30px 18px 30px; line-height:36px; text-align:inherit; background-color:;" height="100%" valign="top" bgcolor="#ffffff" role="module-content"><div><div style="font-family: inherit; text-align: center"><span style="font-size: 43px">Thanks for signing up, {{ user.first_name }}!&nbsp;</span></div><div></div></div></td>
      </tr>
    </tbody>
  </table><table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="a10dcb57-ad22-4f4d-b765-1d427dfddb4e" data-mc-module-version="2019-10-22">
    <tbody>
      <tr>
        <td style="padding:18px 30px 18px 30px; line-height:22px; text-align:inherit; background-color:#ffffff;" height="100%" valign="top" bgcolor="#ffffff" role="module-content"><div><div style="font-family: inherit; text-align: center"><span style="font-size: 18px">Please verify your email address</span></div>
<div style="font-family: inherit; text-align: center"><span style="color: #0F0140; font-size: 18px"><strong>Thank you!&nbsp;</strong></span></div><div></div></div></td>
      </tr>
    </tbody>
  </table><table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="7770fdab-634a-4f62-a277-1c66b2646d8d">
    <tbody>
      <tr>
        <td style="padding:0px 0px 20px 0px;" role="module-content" bgcolor="#ffffff">
        </td>
      </tr>
    </tbody>
  </table><table border="0" cellpadding="0" cellspacing="0" class="module" data-role="module-button" data-type="button" role="module" style="table-layout:fixed;" width="100%" data-muid="d050540f-4672-4f31-80d9-b395dc08abe1">
      <tbody>
        <tr>
          <td align="center" bgcolor="#ffffff" class="outer-td" style="padding:0px 0px 0px 0px;">
            <table border="0" cellpadding="0" cellspacing="0" class="wrapper-mobile" style="text-align:center;">
              <tbody>
                <tr>
                <td align="center" bgcolor="blue" class="inner-td" style="border-radius:6px; font-size:16px; text-align:center; background-color:blue;">
                  <a href="http://{{ domain }}{% url 'account:email-activate' uidb64=uid token=token %}" style="background-color:#0F0140; border:1px solid #122B00; border-color:#122B00; border-radius:0px; border-width:1px; color:white; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 40px 12px 40px; text-align:center; text-decoration:none; border-style:solid; font-family:inherit;" target="_blank">Verify Email Now</a>
                </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table><table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="7770fdab-634a-4f62-a277-1c66b2646d8d.1">
    <tbody>
      <tr>
        <td style="padding:0px 0px 50px 0px;" role="module-content" bgcolor="#ffffff">
        </td>
      </tr>
    </tbody>
  </table></td>
              </tr>
            </tbody>
          </table>
          
        </td>
      </tr>
    </tbody>
  </table><div data-role="module-unsubscribe" class="module" role="module" data-type="unsubscribe" style="color:#444444; font-size:12px; line-height:20px; padding:16px 16px 16px 16px; text-align:Center;" data-muid="4e838cf3-9892-4a6d-94d6-170e474d21e5">
                                            <div class="Unsubscribe--addressLine"><p class="Unsubscribe--senderName" style="font-size:12px; line-height:20px;">Dominik Pioś</p><p style="font-size:12px; line-height:20px;"><span class="Unsubscribe--senderAddress">Lublin</span>, <span class="Unsubscribe--senderCity">Krakowskie Przedmieście</span> <span class="Unsubscribe--senderState">54F</span> <span class="Unsubscribe--senderZip">00-001</span></p></div>
      <tbody>
        <tr>
          <td align="center" bgcolor="" class="outer-td" style="padding:0px 0px 20px 0px;">
            <table border="0" cellpadding="0" cellspacing="0" class="wrapper-mobile" style="text-align:center;">
              <tbody>
                <tr>
                <td align="center" bgcolor="#f5f8fd" class="inner-td" style="border-radius:6px; font-size:16px; text-align:center; background-color:inherit;"><a href="www.google.com" style="background-color:#f5f8fd; border:1px solid #f5f8fd; border-color:#f5f8fd; border-radius:25px; border-width:1px; color:#a8b9d5; display:inline-block; font-size:10px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:5px 18px 5px 18px; text-align:center; text-decoration:none; border-style:solid; font-family:helvetica,sans-serif;" target="_blank">Superb Car Rental © Dominik Pioś 2020</a></td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table></td>
                                      </tr>
                                    </tbody></table>
                                    <!--[if mso]>
                                  </td>
                                </tr>
                              </table>
                            </center>
                            <![endif]-->
                          </td>
                        </tr>
                      </tbody></table>
                    </td>
                  </tr>
                </tbody></table>
              </td>
            </tr>
          </tbody></table>
        </div>
      </center>
    
  
</body></html>